spring:
  application:
    name: spring-secure-api

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
      - org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/demo}
    username: ${SPRING_DATASOURCE_USERNAME:demo}
    password: ${SPRING_DATASOURCE_PASSWORD:demo}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:9090/realms/ilyes-realm/protocol/openid-connect/certs}

aws:
  region: ${AWS_REGION:eu-west-1}

sqs:
  endpoint: ${SQS_ENDPOINT:http://localhost:4566}
  queue:
    api-logs: ${SQS_QUEUE_API_LOGS:queue-api-logs-local}
    security-alerts: ${SQS_QUEUE_SECURITY_ALERTS:queue-security-alerts-local}
